# Generated by Django 5.2.16 on 2026-09-17 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_alter_product_options_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, help_text='Exact URL path (e.g. /, /about, /contact, /products/steel-gratings)', max_length=255, unique=True)),
                ('page_name', models.CharField(help_text="Human-readable label for the admin panel (e.g. 'Homepage', 'About Us')", max_length=150)),
                ('category', models.CharField(choices=[('Core Pages', 'Core Pages'), ('Products', 'Product Categories & Products'), ('Industries', 'Industries'), ('Services', 'Services & Solutions'), ('Locations', 'GCC & Regional Locations'), ('Other', 'Other Pages')], db_index=True, default='Core Pages', max_length=50)),
                ('meta_title', models.CharField(blank=True, help_text='Optimal length: 50-60 characters', max_length=150)),
                ('meta_description', models.TextField(blank=True, help_text='Optimal length: 150-160 characters')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords (e.g. steel gratings, frp grating saudi arabia)', max_length=500)),
                ('canonical_url', models.URLField(blank=True, help_text='Leave blank to use default canonical URL', null=True)),
                ('og_title', models.CharField(blank=True, help_text='Title shown when sharing on WhatsApp/social media', max_length=150)),
                ('og_description', models.TextField(blank=True, help_text='Description snippet shown on social media preview cards')),
                ('no_index', models.BooleanField(default=False, help_text='Check this to instruct search engines NOT to index this page (noindex)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('og_image', models.ForeignKey(blank=True, help_text='Image displayed in WhatsApp/social media link preview', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_pages', to='products.media')),
            ],
            options={
                'verbose_name': 'Page SEO Metadata',
                'verbose_name_plural': 'Page SEO Metadata',
                'ordering': ['category', 'path'],
            },
        ),
    ]
